apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: lms
spec:
  selector:
    app: api-server
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: lms-public-api:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MODE
              value: "local"
            - name: PORT
              value: "5000"
            - name: DATABASE_URL
              value: "postgresql://postgres:itjustworks@local-db:5432/mydb"
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

