apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: lms
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: lms-web:99
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

