apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-web
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-web
  template:
    metadata:
      labels:
        app: lms-web
    spec:
      containers:
        - name: web
          image: lms-web:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lms-web
  namespace: lms
spec:
  selector:
    app: lms-web
  ports:
    - name: http
      port: 80
      targetPort: 80
