apiVersion: v1
kind: Service
metadata:
  name: local-db
  namespace: lms
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: local-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-db
  namespace: lms
spec:
  serviceName: local-db
  replicas: 1
  selector:
    matchLabels:
      app: local-db
  template:
    metadata:
      labels:
        app: local-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "itjustworks"
            - name: POSTGRES_DB
              value: "mydb"
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d mydb"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U postgres -d mydb"]
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

